package layout

object statedatamodel {
    var stateList = listOf<states>(
        states("Alabama", "Yellowhammer State"),
        states("Alaska", "The Last Frontier"),
        states("Arizona", "Grand Canyon State"),
        states("Arkansas", "The Natural State"),
        states("California", "Golden State"),
        states("Colorado", "Centennial State"),
        states("Connecticut", "Constitution State"),
        states("Delaware", "First State"),
        states("Florida", "Sunshine State"),
        states("Georgia", "Peach State"),
        states("Hawaii", "Aloha State"),
        states("Idaho", "Gem State"),
        states("Illinois", "Prairie State"),
        states("Indiana", "Hoosier State"),
        states("Iowa", "Hawkeye State"),
        states("Kansas", "Sunflower State"),
        states("Kentucky", "Bluegrass State"),
        states("Louisiana", "Pelican State"),
        states("Maine", "Pine Tree State"),
        states("Maryland", "Old Line State"),
        states("Massachusetts", "Bay State"),
        states("Michigan", "Great Lakes State"),
        states("Minnesota", "North Star State"),
        states("Mississippi", "Magnolia State"),
        states("Missouri", "Show-Me State"),
        states("Montana", "Treasure State"),
        states("Nebraska", "Cornhusker State"),
        states("Nevada", "Silver State"),
        states("New Hampshire", "Granite State"),
        states("New Jersey", "Garden State"),
        states("New Mexico", "Land of Enchantment"),
        states("New York", "Empire State"),
        states("North Carolina", "Tar Heel State"),
        states("North Dakota", "Peace Garden State"),
        states("Ohio", "Buckeye State"),
        states("Oklahoma", "Sooner State"),
        states("Oregon", "Beaver State"),
        states("Pennsylvania", "Keystone State"),
        states("Rhode Island", "Ocean State"),
        states("South Carolina", "Palmetto State"),
        states("South Dakota", "Mount Rushmore State"),
        states("Tennessee", "Volunteer State"),
        states("Texas", "Lone Star State"),
        states("Utah", "Beehive State"),
        states("Vermont", "Green Mountain State"),
        states("Virginia", "Old Dominion"),
        states("Washington", "Evergreen State"),
        states("West Virginia", "Mountain State"),
        states("Wisconsin", "Badger State"),
        states("Wyoming", "Equality State")

    )
}